//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapDragon.Custom.Pap.WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.ContractHeads = new HashSet<ContractHead>();
            this.ContractHeads1 = new HashSet<ContractHead>();
            this.ContractHeads2 = new HashSet<ContractHead>();
            this.Customer1 = new HashSet<Customer>();
            this.Customer11 = new HashSet<Customer>();
            this.Packs = new HashSet<Pack>();
            this.TransferSentHeads = new HashSet<TransferSentHead>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdTypeUdlvId { get; set; }
        public Nullable<System.Guid> GenderUdlvId { get; set; }
        public Nullable<System.Guid> RaceUdlvId { get; set; }
        public Nullable<System.Guid> HairColorUdlvId { get; set; }
        public Nullable<System.Guid> EyeColorUdlvId { get; set; }
        public Nullable<System.Guid> ApUdlvId { get; set; }
        public Nullable<System.Guid> ArUdlvId { get; set; }
        public Nullable<System.Guid> BillingTermsId { get; set; }
        public System.Guid BillToId { get; set; }
        public Nullable<System.Guid> BrokerUdlvId { get; set; }
        public Nullable<System.Guid> CurrencyUdlvId { get; set; }
        public Nullable<System.Guid> AccountUdlvId { get; set; }
        public Nullable<System.Guid> AccountManagerUdlvId { get; set; }
        public Nullable<System.Guid> PayTermsId { get; set; }
        public System.Guid PayToId { get; set; }
        public int PaymentMethodId { get; set; }
        public string Company { get; set; }
        public string Attention { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string BarCode { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string Phone { get; set; }
        public string Extension { get; set; }
        public string Fax { get; set; }
        public string IdNumber { get; set; }
        public string IdState { get; set; }
        public Nullable<System.DateTime> IdExpires { get; set; }
        public string IdMarks { get; set; }
        public string IdImage { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string CertificateNumber { get; set; }
        public Nullable<System.DateTime> CertificateExpiration { get; set; }
        public string AcctCustomerNumber { get; set; }
        public string FederalIdNumber { get; set; }
        public decimal SellSalesTaxGstAmount { get; set; }
        public decimal SellSalesTaxPstAmount { get; set; }
        public string CheckPayTo { get; set; }
        public string CheckName { get; set; }
        public string CheckAddress1 { get; set; }
        public string CheckAddress2 { get; set; }
        public string CheckCity { get; set; }
        public string CheckState { get; set; }
        public string CheckZip { get; set; }
        public string EmployerName { get; set; }
        public string EmployerAddress1 { get; set; }
        public string EmployerAddress2 { get; set; }
        public string EmployerCity { get; set; }
        public string EmployerState { get; set; }
        public string EmployerZip { get; set; }
        public string EmployerPhone { get; set; }
        public bool BuyFrom { get; set; }
        public bool SellTo { get; set; }
        public bool PayTo { get; set; }
        public bool FreightCarrier { get; set; }
        public bool IsRelated { get; set; }
        public bool SellSalesTaxGst { get; set; }
        public bool SellSalesTaxPst { get; set; }
        public bool ExemptCity { get; set; }
        public bool ExemptPayLimit { get; set; }
        public bool ExemptState { get; set; }
        public int ExtraTicketPriced { get; set; }
        public int ExtraTicketUnpriced { get; set; }
        public int AwardLevel { get; set; }
        public decimal AwardBalance { get; set; }
        public bool BuySalesTaxGst { get; set; }
        public bool BuySalesTaxPst { get; set; }
        public bool ShowPriceOnTicket { get; set; }
        public string SpecialPricingBased { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastActive { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<System.Guid> CreatedInYardId { get; set; }
        public Nullable<System.Guid> HomeYardId { get; set; }
        public string OldPOSITION { get; set; }
        public string OldTITLE { get; set; }
        public string OldTWO_TIX { get; set; }
        public string OldMATRIXNO { get; set; }
        public string OldGROUP1 { get; set; }
        public string OldGROUP2 { get; set; }
        public string OldGROUP3 { get; set; }
        public string OldPAYTO { get; set; }
        public string OldONACCOUNT { get; set; }
        public string OldPAYMETHOD { get; set; }
        public string OldLICENSE { get; set; }
        public string OldSITEID { get; set; }
        public string OldINVWGTCODE { get; set; }
        public string OldTERMS { get; set; }
        public string OldACCT_TYPE { get; set; }
        public string OldBRTRADER { get; set; }
        public string OldIPDELTRK { get; set; }
        public string OldOPEN35760 { get; set; }
        public string OldBALANCE { get; set; }
        public string OldYTDPURCH { get; set; }
        public string OldLSTPURCH { get; set; }
        public string OldYTDPAYM { get; set; }
        public string OldLSTPAYM { get; set; }
        public string OldOPEN1 { get; set; }
        public string OldSPLC_CODE { get; set; }
        public string OldOPEN16 { get; set; }
        public string OldPDISC { get; set; }
        public string OldPDAYS { get; set; }
        public string OldPNET { get; set; }
        public string OldPDESC { get; set; }
        public string OldBILLTO { get; set; }
        public string OldACCTCODE { get; set; }
        public string OldACCTMGR { get; set; }
        public string OldFROMPHONE { get; set; }
        public string OldSGROUP1 { get; set; }
        public string OldSGROUP2 { get; set; }
        public string OldSGROUP3 { get; set; }
        public string OldRACE { get; set; }
        public string OldGENDER { get; set; }
        public string OldHAIRCOLOR { get; set; }
        public string OldEYECOLOR { get; set; }
        public string OldSTARTEDBY { get; set; }
        public string OldIDTYPE { get; set; }
        public string OldPRICENO { get; set; }
        public string OldCURRENCY { get; set; }
        public string OldAPACCT { get; set; }
        public string OldARACCT { get; set; }
        public string OldCERTONFILE { get; set; }
        public string OldSIGONFILE { get; set; }
        public bool IsDefault { get; set; }
        public string CustomerNumber { get; set; }
        public Nullable<System.Guid> BuyTaxCodeUdlvId { get; set; }
        public Nullable<System.Guid> SellTaxCodeUdlvId { get; set; }
        public Nullable<System.Guid> CurrencyId { get; set; }
    
        public virtual ICollection<ContractHead> ContractHeads { get; set; }
        public virtual ICollection<ContractHead> ContractHeads1 { get; set; }
        public virtual ICollection<ContractHead> ContractHeads2 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue1 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue2 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue3 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue4 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue5 { get; set; }
        public virtual ICollection<Customer> Customer1 { get; set; }
        public virtual Customer Customer2 { get; set; }
        public virtual ICollection<Customer> Customer11 { get; set; }
        public virtual Customer Customer3 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue6 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue7 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue8 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue9 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue10 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue11 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue12 { get; set; }
        public virtual Yard Yard { get; set; }
        public virtual Yard Yard1 { get; set; }
        public virtual ICollection<Pack> Packs { get; set; }
        public virtual ICollection<TransferSentHead> TransferSentHeads { get; set; }
    }
}
