//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapDragon.Custom.Pap.WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralOption
    {
        public System.Guid Id { get; set; }
        public System.Guid YardId { get; set; }
        public Nullable<System.Guid> LoyaltyTierUdlvId { get; set; }
        public bool UseLogoOnReports { get; set; }
        public bool NtepEnforce { get; set; }
        public bool InventoryUpdate { get; set; }
        public bool AllowDecimal { get; set; }
        public bool ComputeLoyaltyRewards { get; set; }
        public byte[] LogoImage { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string JpeggerInternalIpAddress { get; set; }
        public int JpeggerInternalIpPort { get; set; }
        public string JpeggerExternalIpAddress { get; set; }
        public int JpeggerExternalIpPort { get; set; }
        public bool JpeggerUseLocationCode { get; set; }
        public string JpeggerLocationCode { get; set; }
        public bool JpeggerSaveIdImageOnTicketClose { get; set; }
        public string JpeggerThumbnailImagesPath { get; set; }
        public string JpeggerLicenseImagesPath { get; set; }
        public string MobileSignatureCamera { get; set; }
        public string MobileSignaturePath { get; set; }
        public int JpeggerTimeOutCounter { get; set; }
        public System.Guid CurrencyId { get; set; }
        public string CurrentInventoryMonth { get; set; }
        public bool InventoryFirstInFirstOut { get; set; }
        public int DefaultScaleWeight { get; set; }
        public string CurrentInventoryYear { get; set; }
        public System.Guid LanguageId { get; set; }
        public bool UseExternalJpeggerViewer { get; set; }
        public bool RoundLoyaltyRewards { get; set; }
        public Nullable<int> LoyaltyTier { get; set; }
        public bool JpeggerUseFetch { get; set; }
        public string JpeggerFetchLocation { get; set; }
        public string RulesEngineFileLocation { get; set; }
        public string RulesEngineFileName { get; set; }
        public int AccountingSystemType { get; set; }
    
        public virtual Yard Yard { get; set; }
    }
}
