//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapDragon.Custom.Pap.WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.ContractItems = new HashSet<ContractItem>();
            this.Packs = new HashSet<Pack>();
            this.PackLogs = new HashSet<PackLog>();
            this.TransferSentItems = new HashSet<TransferSentItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid YardId { get; set; }
        public string Code { get; set; }
        public bool IsDisabled { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string PrintDescription { get; set; }
        public bool Taxable { get; set; }
        public Nullable<System.Guid> PackTypeUdlvId { get; set; }
        public System.Guid CommodityTypeUdlvId { get; set; }
        public Nullable<System.Guid> ReportGroupTypeUdlvId { get; set; }
        public Nullable<System.Guid> DefaultUomId { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.Guid> PriceUomId { get; set; }
        public decimal MinPrice { get; set; }
        public Nullable<System.Guid> MinPriceUomId { get; set; }
        public string ForegroundColor { get; set; }
        public string BackgroundColor { get; set; }
        public int TextSize { get; set; }
        public string MenuText { get; set; }
        public string UnitInventory { get; set; }
        public string GeneralLedgerIdCode { get; set; }
        public Nullable<System.Guid> GlPurchasesThirdPartyUdlvId { get; set; }
        public Nullable<System.Guid> GlSalesThirdPartyUdlvId { get; set; }
        public Nullable<System.Guid> GlCogsThirdPartyUdlvId { get; set; }
        public Nullable<System.Guid> GlPurchasesRelatedCompanyUdlvId { get; set; }
        public Nullable<System.Guid> GlSalesRelatedCompanyUdlvId { get; set; }
        public Nullable<System.Guid> GlCogsRelatedCompanyUdlvId { get; set; }
        public bool InventoryProcessingDisabled { get; set; }
        public decimal ShippingTolerance { get; set; }
        public Nullable<System.Guid> DefaultLocationId { get; set; }
        public Nullable<System.Guid> DefaultLocationRowId { get; set; }
    
        public virtual ICollection<ContractItem> ContractItems { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue1 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue2 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue3 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue4 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue5 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue6 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue7 { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue8 { get; set; }
        public virtual Yard Yard { get; set; }
        public virtual ICollection<Pack> Packs { get; set; }
        public virtual ICollection<PackLog> PackLogs { get; set; }
        public virtual ICollection<TransferSentItem> TransferSentItems { get; set; }
    }
}
