//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapDragon.Custom.Pap.WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackListItem
    {
        public System.Guid Id { get; set; }
        public System.Guid ContractItemId { get; set; }
        public System.Guid PackListHeadId { get; set; }
        public System.Guid PackId { get; set; }
        public int Units { get; set; }
    
        public virtual ContractItem ContractItem { get; set; }
        public virtual Pack Pack { get; set; }
        public virtual PackListHead PackListHead { get; set; }
    }
}
