//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapDragon.Custom.Pap.WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pack
    {
        public Pack()
        {
            this.PackListItems = new HashSet<PackListItem>();
            this.PackLogs = new HashSet<PackLog>();
            this.TransferPackListItems = new HashSet<TransferPackListItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid InventoryId { get; set; }
        public System.Guid YardId { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public Nullable<System.Guid> RowId { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public System.Guid PackTypeUdlvId { get; set; }
        public long TagNumber { get; set; }
        public int PackStatus { get; set; }
        public decimal GrossWeight { get; set; }
        public decimal TareWeight { get; set; }
        public decimal NetWeight { get; set; }
        public decimal ScaleGrossWeight { get; set; }
        public decimal ScaleTareWeight { get; set; }
        public string UnitOfMeasure { get; set; }
        public string PrintDescription { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<System.DateTime> VoidDate { get; set; }
        public Nullable<System.Guid> VoidedByUserId { get; set; }
        public Nullable<System.DateTime> PackLockedOn { get; set; }
        public string PackLockedWorkstation { get; set; }
        public Nullable<System.Guid> PackLockedByUserId { get; set; }
        public string NumberPrefix { get; set; }
        public decimal Quantity { get; set; }
        public decimal Cost { get; set; }
        public string InternalPackNumber { get; set; }
        public bool InternalNumberEdited { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue { get; set; }
        public virtual Yard Yard { get; set; }
        public virtual ICollection<PackListItem> PackListItems { get; set; }
        public virtual ICollection<PackLog> PackLogs { get; set; }
        public virtual ICollection<TransferPackListItem> TransferPackListItems { get; set; }
    }
}
