//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapDragon.Custom.Pap.WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackListHead
    {
        public PackListHead()
        {
            this.PackListItems = new HashSet<PackListItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractHeadId { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public long PackListNumber { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string SealNumber { get; set; }
        public int PackListStatus { get; set; }
        public Nullable<System.Guid> LockedByUserId { get; set; }
        public Nullable<System.DateTime> LockedOn { get; set; }
        public string LockedWorkstation { get; set; }
    
        public virtual ContractHead ContractHead { get; set; }
        public virtual ICollection<PackListItem> PackListItems { get; set; }
    }
}
