//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapDragon.Custom.Pap.WebService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContractHead> ContractHeads { get; set; }
        public virtual DbSet<ContractItem> ContractItems { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<GeneralOption> GeneralOptions { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Pack> Packs { get; set; }
        public virtual DbSet<PackListHead> PackListHeads { get; set; }
        public virtual DbSet<PackListItem> PackListItems { get; set; }
        public virtual DbSet<PackLog> PackLogs { get; set; }
        public virtual DbSet<TransferPackListHead> TransferPackListHeads { get; set; }
        public virtual DbSet<TransferPackListItem> TransferPackListItems { get; set; }
        public virtual DbSet<TransferSentHead> TransferSentHeads { get; set; }
        public virtual DbSet<TransferSentItem> TransferSentItems { get; set; }
        public virtual DbSet<UniqueNumber> UniqueNumbers { get; set; }
        public virtual DbSet<UserDefinedList> UserDefinedLists { get; set; }
        public virtual DbSet<UserDefinedListValue> UserDefinedListValues { get; set; }
        public virtual DbSet<Yard> Yards { get; set; }
    }
}
