//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapDragon.Custom.Pap.WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferPackListItem
    {
        public System.Guid Id { get; set; }
        public System.Guid TransferPackListHeadId { get; set; }
        public System.Guid TransferSentItemId { get; set; }
        public System.Guid PackId { get; set; }
    
        public virtual Pack Pack { get; set; }
        public virtual TransferPackListHead TransferPackListHead { get; set; }
        public virtual TransferPackListItem TransferPackListItem1 { get; set; }
        public virtual TransferPackListItem TransferPackListItem2 { get; set; }
        public virtual TransferSentItem TransferSentItem { get; set; }
    }
}
