//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapDragon.Custom.Pap.WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferPackListHead
    {
        public TransferPackListHead()
        {
            this.TransferSentHeads = new HashSet<TransferSentHead>();
            this.TransferPackListItems = new HashSet<TransferPackListItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid TransferSentHeadId { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public long PackListNumber { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string SealNumber { get; set; }
        public int PackListStatus { get; set; }
    
        public virtual ICollection<TransferSentHead> TransferSentHeads { get; set; }
        public virtual TransferSentHead TransferSentHead { get; set; }
        public virtual ICollection<TransferPackListItem> TransferPackListItems { get; set; }
    }
}
