//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapDragon.Custom.Pap.WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniqueNumber
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> YardId { get; set; }
        public string Type { get; set; }
        public long NextNumber { get; set; }
        public int NumberType { get; set; }
    
        public virtual Yard Yard { get; set; }
    }
}
