//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapDragon.Custom.Pap.WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDefinedListValue
    {
        public UserDefinedListValue()
        {
            this.ContractHeads = new HashSet<ContractHead>();
            this.ContractHeads1 = new HashSet<ContractHead>();
            this.ContractHeads2 = new HashSet<ContractHead>();
            this.ContractHeads3 = new HashSet<ContractHead>();
            this.ContractHeads4 = new HashSet<ContractHead>();
            this.ContractHeads5 = new HashSet<ContractHead>();
            this.Customers = new HashSet<Customer>();
            this.Customers1 = new HashSet<Customer>();
            this.Customers2 = new HashSet<Customer>();
            this.Customers3 = new HashSet<Customer>();
            this.Customers4 = new HashSet<Customer>();
            this.Customers5 = new HashSet<Customer>();
            this.Customers6 = new HashSet<Customer>();
            this.Customers7 = new HashSet<Customer>();
            this.Customers8 = new HashSet<Customer>();
            this.Customers9 = new HashSet<Customer>();
            this.Customers10 = new HashSet<Customer>();
            this.Customers11 = new HashSet<Customer>();
            this.Customers12 = new HashSet<Customer>();
            this.Inventories = new HashSet<Inventory>();
            this.Inventories1 = new HashSet<Inventory>();
            this.Inventories2 = new HashSet<Inventory>();
            this.Inventories3 = new HashSet<Inventory>();
            this.Inventories4 = new HashSet<Inventory>();
            this.Inventories5 = new HashSet<Inventory>();
            this.Inventories6 = new HashSet<Inventory>();
            this.Inventories7 = new HashSet<Inventory>();
            this.Inventories8 = new HashSet<Inventory>();
            this.Packs = new HashSet<Pack>();
            this.TransferSentHeads = new HashSet<TransferSentHead>();
            this.Yards = new HashSet<Yard>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ListId { get; set; }
        public string CodeValue { get; set; }
        public string ReportDescription { get; set; }
        public bool IsDisabled { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual ICollection<ContractHead> ContractHeads { get; set; }
        public virtual ICollection<ContractHead> ContractHeads1 { get; set; }
        public virtual ICollection<ContractHead> ContractHeads2 { get; set; }
        public virtual ICollection<ContractHead> ContractHeads3 { get; set; }
        public virtual ICollection<ContractHead> ContractHeads4 { get; set; }
        public virtual ICollection<ContractHead> ContractHeads5 { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Customer> Customers1 { get; set; }
        public virtual ICollection<Customer> Customers2 { get; set; }
        public virtual ICollection<Customer> Customers3 { get; set; }
        public virtual ICollection<Customer> Customers4 { get; set; }
        public virtual ICollection<Customer> Customers5 { get; set; }
        public virtual ICollection<Customer> Customers6 { get; set; }
        public virtual ICollection<Customer> Customers7 { get; set; }
        public virtual ICollection<Customer> Customers8 { get; set; }
        public virtual ICollection<Customer> Customers9 { get; set; }
        public virtual ICollection<Customer> Customers10 { get; set; }
        public virtual ICollection<Customer> Customers11 { get; set; }
        public virtual ICollection<Customer> Customers12 { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<Inventory> Inventories1 { get; set; }
        public virtual ICollection<Inventory> Inventories2 { get; set; }
        public virtual ICollection<Inventory> Inventories3 { get; set; }
        public virtual ICollection<Inventory> Inventories4 { get; set; }
        public virtual ICollection<Inventory> Inventories5 { get; set; }
        public virtual ICollection<Inventory> Inventories6 { get; set; }
        public virtual ICollection<Inventory> Inventories7 { get; set; }
        public virtual ICollection<Inventory> Inventories8 { get; set; }
        public virtual ICollection<Pack> Packs { get; set; }
        public virtual ICollection<TransferSentHead> TransferSentHeads { get; set; }
        public virtual UserDefinedList UserDefinedList { get; set; }
        public virtual ICollection<Yard> Yards { get; set; }
    }
}
