//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapDragon.Custom.Pap.WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDefinedList
    {
        public UserDefinedList()
        {
            this.UserDefinedListValues = new HashSet<UserDefinedListValue>();
        }
    
        public System.Guid Id { get; set; }
        public string CodeMast { get; set; }
        public string CodeMastEnum { get; set; }
        public bool IsDisabled { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual ICollection<UserDefinedListValue> UserDefinedListValues { get; set; }
    }
}
