//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapDragon.Custom.Pap.WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yard
    {
        public Yard()
        {
            this.ContractHeads = new HashSet<ContractHead>();
            this.Customers = new HashSet<Customer>();
            this.Customers1 = new HashSet<Customer>();
            this.GeneralOptions = new HashSet<GeneralOption>();
            this.Inventories = new HashSet<Inventory>();
            this.Packs = new HashSet<Pack>();
            this.TransferSentHeads = new HashSet<TransferSentHead>();
            this.TransferSentHeads1 = new HashSet<TransferSentHead>();
            this.UniqueNumbers = new HashSet<UniqueNumber>();
            this.Yard1 = new HashSet<Yard>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CompanyTypeUdlvId { get; set; }
        public Nullable<System.Guid> ParentCompanyId { get; set; }
        public string CompanyIdentifier { get; set; }
        public string YardName { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Division { get; set; }
        public string DealerIdentifier { get; set; }
        public string Memo { get; set; }
        public bool Headquarters { get; set; }
        public bool IsDisabled { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CustomerNumberPrefix { get; set; }
    
        public virtual ICollection<ContractHead> ContractHeads { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Customer> Customers1 { get; set; }
        public virtual ICollection<GeneralOption> GeneralOptions { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<Pack> Packs { get; set; }
        public virtual ICollection<TransferSentHead> TransferSentHeads { get; set; }
        public virtual ICollection<TransferSentHead> TransferSentHeads1 { get; set; }
        public virtual ICollection<UniqueNumber> UniqueNumbers { get; set; }
        public virtual UserDefinedListValue UserDefinedListValue { get; set; }
        public virtual ICollection<Yard> Yard1 { get; set; }
        public virtual Yard Yard2 { get; set; }
    }
}
